use bitflags::bitflags;
use winapi::shared::{dxgi, dxgi1_6, dxgiformat};

mod adapter;
mod factory;
mod swapchain;

pub use self::adapter::{Adapter, AdapterInfo};
pub use self::factory::Factory;
pub use self::swapchain::{
    AlphaMode, BufferUsage, SampleDesc, Scaling, SwapChain, SwapChainDesc, SwapChainFlags,
    SwapEffect,
};

#[repr(u32)]
#[derive(Copy, Clone, Debug)]
pub enum GpuPreference {
    Unspecified = dxgi1_6::DXGI_GPU_PREFERENCE_UNSPECIFIED,
    MinimumPower = dxgi1_6::DXGI_GPU_PREFERENCE_MINIMUM_POWER,
    HighPerformance = dxgi1_6::DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,
}

#[repr(u32)]
#[derive(Copy, Clone, Debug)]
#[allow(non_camel_case_types)]
pub enum Format {
    UNKNOWN = dxgiformat::DXGI_FORMAT_UNKNOWN,
    R32G32B32A32_TYPELESS = dxgiformat::DXGI_FORMAT_R32G32B32A32_TYPELESS,
    R32G32B32A32_FLOAT = dxgiformat::DXGI_FORMAT_R32G32B32A32_FLOAT,
    R32G32B32A32_UINT = dxgiformat::DXGI_FORMAT_R32G32B32A32_UINT,
    R32G32B32A32_SINT = dxgiformat::DXGI_FORMAT_R32G32B32A32_SINT,
    R32G32B32_TYPELESS = dxgiformat::DXGI_FORMAT_R32G32B32_TYPELESS,
    R32G32B32_FLOAT = dxgiformat::DXGI_FORMAT_R32G32B32_FLOAT,
    R32G32B32_UINT = dxgiformat::DXGI_FORMAT_R32G32B32_UINT,
    R32G32B32_SINT = dxgiformat::DXGI_FORMAT_R32G32B32_SINT,
    R16G16B16A16_TYPELESS = dxgiformat::DXGI_FORMAT_R16G16B16A16_TYPELESS,
    R16G16B16A16_FLOAT = dxgiformat::DXGI_FORMAT_R16G16B16A16_FLOAT,
    R16G16B16A16_UNORM = dxgiformat::DXGI_FORMAT_R16G16B16A16_UNORM,
    R16G16B16A16_UINT = dxgiformat::DXGI_FORMAT_R16G16B16A16_UINT,
    R16G16B16A16_SNORM = dxgiformat::DXGI_FORMAT_R16G16B16A16_SNORM,
    R16G16B16A16_SINT = dxgiformat::DXGI_FORMAT_R16G16B16A16_SINT,
    R32G32_TYPELESS = dxgiformat::DXGI_FORMAT_R32G32_TYPELESS,
    R32G32_FLOAT = dxgiformat::DXGI_FORMAT_R32G32_FLOAT,
    R32G32_UINT = dxgiformat::DXGI_FORMAT_R32G32_UINT,
    R32G32_SINT = dxgiformat::DXGI_FORMAT_R32G32_SINT,
    R32G8X24_TYPELESS = dxgiformat::DXGI_FORMAT_R32G8X24_TYPELESS,
    D32_FLOAT_S8X24_UINT = dxgiformat::DXGI_FORMAT_D32_FLOAT_S8X24_UINT,
    R32_FLOAT_X8X24_TYPELESS = dxgiformat::DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS,
    X32_TYPELESS_G8X24_UINT = dxgiformat::DXGI_FORMAT_X32_TYPELESS_G8X24_UINT,
    R10G10B10A2_TYPELESS = dxgiformat::DXGI_FORMAT_R10G10B10A2_TYPELESS,
    R10G10B10A2_UNORM = dxgiformat::DXGI_FORMAT_R10G10B10A2_UNORM,
    R10G10B10A2_UINT = dxgiformat::DXGI_FORMAT_R10G10B10A2_UINT,
    R11G11B10_FLOAT = dxgiformat::DXGI_FORMAT_R11G11B10_FLOAT,
    R8G8B8A8_TYPELESS = dxgiformat::DXGI_FORMAT_R8G8B8A8_TYPELESS,
    R8G8B8A8_UNORM = dxgiformat::DXGI_FORMAT_R8G8B8A8_UNORM,
    R8G8B8A8_UNORM_SRGB = dxgiformat::DXGI_FORMAT_R8G8B8A8_UNORM_SRGB,
    R8G8B8A8_UINT = dxgiformat::DXGI_FORMAT_R8G8B8A8_UINT,
    R8G8B8A8_SNORM = dxgiformat::DXGI_FORMAT_R8G8B8A8_SNORM,
    R8G8B8A8_SINT = dxgiformat::DXGI_FORMAT_R8G8B8A8_SINT,
    R16G16_TYPELESS = dxgiformat::DXGI_FORMAT_R16G16_TYPELESS,
    R16G16_FLOAT = dxgiformat::DXGI_FORMAT_R16G16_FLOAT,
    R16G16_UNORM = dxgiformat::DXGI_FORMAT_R16G16_UNORM,
    R16G16_UINT = dxgiformat::DXGI_FORMAT_R16G16_UINT,
    R16G16_SNORM = dxgiformat::DXGI_FORMAT_R16G16_SNORM,
    R16G16_SINT = dxgiformat::DXGI_FORMAT_R16G16_SINT,
    R32_TYPELESS = dxgiformat::DXGI_FORMAT_R32_TYPELESS,
    D32_FLOAT = dxgiformat::DXGI_FORMAT_D32_FLOAT,
    R32_FLOAT = dxgiformat::DXGI_FORMAT_R32_FLOAT,
    R32_UINT = dxgiformat::DXGI_FORMAT_R32_UINT,
    R32_SINT = dxgiformat::DXGI_FORMAT_R32_SINT,
    R24G8_TYPELESS = dxgiformat::DXGI_FORMAT_R24G8_TYPELESS,
    D24_UNORM_S8_UINT = dxgiformat::DXGI_FORMAT_D24_UNORM_S8_UINT,
    R24_UNORM_X8_TYPELESS = dxgiformat::DXGI_FORMAT_R24_UNORM_X8_TYPELESS,
    X24_TYPELESS_G8_UINT = dxgiformat::DXGI_FORMAT_X24_TYPELESS_G8_UINT,
    R8G8_TYPELESS = dxgiformat::DXGI_FORMAT_R8G8_TYPELESS,
    R8G8_UNORM = dxgiformat::DXGI_FORMAT_R8G8_UNORM,
    R8G8_UINT = dxgiformat::DXGI_FORMAT_R8G8_UINT,
    R8G8_SNORM = dxgiformat::DXGI_FORMAT_R8G8_SNORM,
    R8G8_SINT = dxgiformat::DXGI_FORMAT_R8G8_SINT,
    R16_TYPELESS = dxgiformat::DXGI_FORMAT_R16_TYPELESS,
    R16_FLOAT = dxgiformat::DXGI_FORMAT_R16_FLOAT,
    D16_UNORM = dxgiformat::DXGI_FORMAT_D16_UNORM,
    R16_UNORM = dxgiformat::DXGI_FORMAT_R16_UNORM,
    R16_UINT = dxgiformat::DXGI_FORMAT_R16_UINT,
    R16_SNORM = dxgiformat::DXGI_FORMAT_R16_SNORM,
    R16_SINT = dxgiformat::DXGI_FORMAT_R16_SINT,
    R8_TYPELESS = dxgiformat::DXGI_FORMAT_R8_TYPELESS,
    R8_UNORM = dxgiformat::DXGI_FORMAT_R8_UNORM,
    R8_UINT = dxgiformat::DXGI_FORMAT_R8_UINT,
    R8_SNORM = dxgiformat::DXGI_FORMAT_R8_SNORM,
    R8_SINT = dxgiformat::DXGI_FORMAT_R8_SINT,
    A8_UNORM = dxgiformat::DXGI_FORMAT_A8_UNORM,
    R1_UNORM = dxgiformat::DXGI_FORMAT_R1_UNORM,
    R9G9B9E5_SHAREDEXP = dxgiformat::DXGI_FORMAT_R9G9B9E5_SHAREDEXP,
    R8G8_B8G8_UNORM = dxgiformat::DXGI_FORMAT_R8G8_B8G8_UNORM,
    G8R8_G8B8_UNORM = dxgiformat::DXGI_FORMAT_G8R8_G8B8_UNORM,
    BC1_TYPELESS = dxgiformat::DXGI_FORMAT_BC1_TYPELESS,
    BC1_UNORM = dxgiformat::DXGI_FORMAT_BC1_UNORM,
    BC1_UNORM_SRGB = dxgiformat::DXGI_FORMAT_BC1_UNORM_SRGB,
    BC2_TYPELESS = dxgiformat::DXGI_FORMAT_BC2_TYPELESS,
    BC2_UNORM = dxgiformat::DXGI_FORMAT_BC2_UNORM,
    BC2_UNORM_SRGB = dxgiformat::DXGI_FORMAT_BC2_UNORM_SRGB,
    BC3_TYPELESS = dxgiformat::DXGI_FORMAT_BC3_TYPELESS,
    BC3_UNORM = dxgiformat::DXGI_FORMAT_BC3_UNORM,
    BC3_UNORM_SRGB = dxgiformat::DXGI_FORMAT_BC3_UNORM_SRGB,
    BC4_TYPELESS = dxgiformat::DXGI_FORMAT_BC4_TYPELESS,
    BC4_UNORM = dxgiformat::DXGI_FORMAT_BC4_UNORM,
    BC4_SNORM = dxgiformat::DXGI_FORMAT_BC4_SNORM,
    BC5_TYPELESS = dxgiformat::DXGI_FORMAT_BC5_TYPELESS,
    BC5_UNORM = dxgiformat::DXGI_FORMAT_BC5_UNORM,
    BC5_SNORM = dxgiformat::DXGI_FORMAT_BC5_SNORM,
    B5G6R5_UNORM = dxgiformat::DXGI_FORMAT_B5G6R5_UNORM,
    B5G5R5A1_UNORM = dxgiformat::DXGI_FORMAT_B5G5R5A1_UNORM,
    B8G8R8A8_UNORM = dxgiformat::DXGI_FORMAT_B8G8R8A8_UNORM,
    B8G8R8X8_UNORM = dxgiformat::DXGI_FORMAT_B8G8R8X8_UNORM,
    R10G10B10_XR_BIAS_A2_UNORM = dxgiformat::DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM,
    B8G8R8A8_TYPELESS = dxgiformat::DXGI_FORMAT_B8G8R8A8_TYPELESS,
    B8G8R8A8_UNORM_SRGB = dxgiformat::DXGI_FORMAT_B8G8R8A8_UNORM_SRGB,
    B8G8R8X8_TYPELESS = dxgiformat::DXGI_FORMAT_B8G8R8X8_TYPELESS,
    B8G8R8X8_UNORM_SRGB = dxgiformat::DXGI_FORMAT_B8G8R8X8_UNORM_SRGB,
    BC6H_TYPELESS = dxgiformat::DXGI_FORMAT_BC6H_TYPELESS,
    BC6H_UF16 = dxgiformat::DXGI_FORMAT_BC6H_UF16,
    BC6H_SF16 = dxgiformat::DXGI_FORMAT_BC6H_SF16,
    BC7_TYPELESS = dxgiformat::DXGI_FORMAT_BC7_TYPELESS,
    BC7_UNORM = dxgiformat::DXGI_FORMAT_BC7_UNORM,
    BC7_UNORM_SRGB = dxgiformat::DXGI_FORMAT_BC7_UNORM_SRGB,
    AYUV = dxgiformat::DXGI_FORMAT_AYUV,
    Y410 = dxgiformat::DXGI_FORMAT_Y410,
    Y416 = dxgiformat::DXGI_FORMAT_Y416,
    NV12 = dxgiformat::DXGI_FORMAT_NV12,
    P010 = dxgiformat::DXGI_FORMAT_P010,
    P016 = dxgiformat::DXGI_FORMAT_P016,
    F420_OPAQUE = dxgiformat::DXGI_FORMAT_420_OPAQUE,
    YUY2 = dxgiformat::DXGI_FORMAT_YUY2,
    Y210 = dxgiformat::DXGI_FORMAT_Y210,
    Y216 = dxgiformat::DXGI_FORMAT_Y216,
    NV11 = dxgiformat::DXGI_FORMAT_NV11,
    AI44 = dxgiformat::DXGI_FORMAT_AI44,
    IA44 = dxgiformat::DXGI_FORMAT_IA44,
    P8 = dxgiformat::DXGI_FORMAT_P8,
    A8P8 = dxgiformat::DXGI_FORMAT_A8P8,
    B4G4R4A4_UNORM = dxgiformat::DXGI_FORMAT_B4G4R4A4_UNORM,
    P208 = dxgiformat::DXGI_FORMAT_P208,
    V208 = dxgiformat::DXGI_FORMAT_V208,
    V408 = dxgiformat::DXGI_FORMAT_V408,
}

bitflags! {
    pub struct PresentFlags: u32 {
        const NONE = 0;
        const DO_NOT_SEQUENCE = dxgi::DXGI_PRESENT_DO_NOT_SEQUENCE;
        const TEST = dxgi::DXGI_PRESENT_TEST;
        const RESTART = dxgi::DXGI_PRESENT_RESTART;
        const DO_NOT_WAIT = dxgi::DXGI_PRESENT_DO_NOT_WAIT;
        const RESTRICT_TO_OUTPUT = dxgi::DXGI_PRESENT_RESTRICT_TO_OUTPUT;
        const PREFER_RIGHT = dxgi::DXGI_PRESENT_STEREO_PREFER_RIGHT;
        const STEREO_TEMPORARY_MONO = dxgi::DXGI_PRESENT_STEREO_TEMPORARY_MONO;
        const USE_DURATION = dxgi::DXGI_PRESENT_USE_DURATION;
        const ALLOW_TEARING = dxgi::DXGI_PRESENT_ALLOW_TEARING;
    }
}

bitflags! {
    pub struct WindowAssociationFlags: u32 {
        const NO_WINDOW_CHANGES = 1;
        const NO_ALT_ENTER = 1 << 1;
        const NO_PRINT_SCREEN = 1 << 2;
        const VALID = 0x7;
    }
}
